### ISSUE TITLE
load runners from config files

### ISSUE THREAD

**Issue by anna-singleton** [anna-singleton/runfast#1]
Loading `runner`s from config files makes this usable without touching the internal code *theoretically*, as this would obviously require recompilation which is not ideal.

Current way i want this to work is by using `.toml` files to hold information about runners (name, command, whether they accept additional arguments, should they exit instantly after the runner command finishes etc.). We would then load from `/etc/runfast.toml` and then `~/.config/runfast/runners.toml` , overwriting any name clashes, preferring the user-level one.

Example config entries:
```toml
[rust run]
cmd = "cargo"
args = [ "run" ]
exit_fast = false

[python]
cmd = "python"
args = [ "main.py" ]
```
